### ISSUE TITLE
Missing a requirement in sentence tokenization

### ISSUE THREAD

**Issue by jzohrab** [PyThaiNLP/tutorials#27]
Hello, thank you for your project and documentation!

In https://pythainlp.org/tutorials/notebooks/pythainlp_get_started.html#Sentence, I was trying the example:

```
from pythainlp import sent_tokenize

text = ("พระราชบัญญัติธรรมนูญการปกครองแผ่นดินสยามชั่วคราว พุทธศักราช ๒๔๗๕ "
        "เป็นรัฐธรรมนูญฉบับชั่วคราว ซึ่งถือว่าเป็นรัฐธรรมนูญฉบับแรกแห่งราชอาณาจักรสยาม "
        "ประกาศใช้เมื่อวันที่ 27 มิถุนายน พ.ศ. 2475 "
        "โดยเป็นผลพวงหลังการปฏิวัติเมื่อวันที่ 24 มิถุนายน พ.ศ. 2475 โดยคณะราษฎร")

print("default (crfcut):")
print(sent_tokenize(text))
```
In my venv, which only has pip installed pythainlp, I get the following error:

```
default (crfcut):
Traceback (most recent call last):
  File "/Users/jeff/Documents/Projects/lute_thai_testing/main.py", line 9, in <module>
    print(sent_tokenize(text))
  File "/Users/jeff/Documents/Projects/lute_thai_testing/myenv/lib/python3.9/site-packages/pythainlp/tokenize/core.py", line 403, in sent_tokenize
    from pythainlp.tokenize.crfcut import segment
  File "/Users/jeff/Documents/Projects/lute_thai_testing/myenv/lib/python3.9/site-packages/pythainlp/tokenize/crfcut.py", line 22, in <module>
    import pycrfsuite
ModuleNotFoundError: No module named 'pycrfsuite'
```

I haven't looked for a solution yet, am just hacking around.  Thought you should know.  Cheers!

**Comment by wannaphong** [comment]
Hello! Thank you for your report.

You need to install python-crfsuite (pip install python-crfsuite) before use sent_tokenize. https://github.com/PyThaiNLP/pythainlp/issues/859

We have often installation problems from python-crfsuite and we are trying to remove all crfsuite but it is still work in progress.

**Comment by jzohrab** [comment]
Thank you @wannaphong :wave:

Later on that same page is a reference to "pip install attacut", but when I try that on my mac I get the following:

```
ERROR: Could not find a version that satisfies the requirement torch>=1.2.0 (from attacut) (from versions: none)
ERROR: No matching distribution found for torch>=1.2.0 (from attacut)
```

**Comment by wannaphong** [comment]
> Thank you @wannaphong :wave:
> 
> 
> 
> Later on that same page is a reference to "pip install attacut", but when I try that on my mac I get the following:
> 
> 
> 
> ```
> 
> ERROR: Could not find a version that satisfies the requirement torch>=1.2.0 (from attacut) (from versions: none)
> 
> ERROR: No matching distribution found for torch>=1.2.0 (from attacut)
> 
> ```

I suggest you should install torch before installing attacut. https://pypi.org/project/torch/2.4.1/#description

**Comment by jzohrab** [comment]
Thanks again @wannaphong -- I'll leave this to you to close, unless you want to use it to revise the documentation.  :wave:
